.travis.yml

Previously Travis-CI would only test against the version of MongoDB that was officially supported (2.4.x as of this PR). This PR instead sets up an build matrix that tests against the following MongoDB versions:
- 2.4.x
- 2.6.x
- 2.8.x
- 3.0.x
When running it will try and fetch the latest patch version of each minor version.

Setup Travis-CI build matrix with differnt MongoDB versions

---

package.json

Version 1.4.19 of mongodb native driver fails to build native bson driver on windows with node 0.12 installed

Update to mongodb 1.4.32

---

package.json

The latest (`mongodb-core@1.1.33`) fixes errors in mongodb-core (`@1.1.9`) where the `bson` C++ extension fails to build and then complains loudly about it every time the module is instantiated. 
Gets rid of this:
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Update mongodb-core patch level

---

lib/collection.js

Currently if calling ensureIndex with options but without cb an error is throw in mongodb core caused by an undefined callback. This fix checks if a callback was given otherwise it reinvokes createIndex with noop callback.

Add check for cb undefined in createIndex

---

lib/collection.js
test/test-aggregate-pipeline.js

Allow for both `aggregate({stage}, {stage}, cb)` as well as a
`aggregate([{stage}, {stage}], cb)`

Allow array-based aggregation pipelines

---

lib/bulk.js
test/test-bulk-updates.js

Add upsert() method for Bulk.find to allow the insertion of new documents when there are no matches with the update and updateOne methods.

Add upsert() method for Bulk.find

---

README.md
index.js
lib/get-topology.js

Add support to connect using different authentication mechanisms with a new options argument. 
Fixes: https://github.com/mafintosh/mongojs/issues/208
A PR has also been made to prevent having to requiring in ScramSHA1. 
https://github.com/christkv/mongodb-core/pull/28

Add support for ScramSHA1

---

lib/collection.js

mongodb-core doesn't pass an error object in certain cases, such as on duplicate key errors.  This change checks the result's `writeErrors` property and, if it's populated, passes the first error back.
This should fix #235 and #197.

Fixed insert error detection and passing

---

index.js

Previusly only the `ObjectId` function was exposed and available directly from the root of the `mongojs` module.
This commit exposes a couple of other BSON types in the same manner. This is now the full list of exposed types:
- `mongojs.ObjectId`
- `mongojs.DBRef`
- `mongojs.Timestamp`
- `mongojs.MinKey`
- `mongojs.MaxKey`
- `mongojs.NumberLong` (the BSON type `Long`)
This is actually a revival commit, bringing back the spirit of the very first Pull Request ever made to this projeect back in 2011 (later refined in commit 06bbf02): #1

Expose bson stuff visible in the shell

---

lib/collection.js

I don't think it should be calling createIndex.

Fix handling default arguments in ensureIndex

---

lib/collection.js

Added wrapper around the [rename](http://mongodb.github.io/node-mongodb-native/api-generated/collection.html#rename) command to rename a collection.

Wrapper to rename a collection

---

package.json

@watson @mafintosh This branch is using tap-spec to run tests which gives a much nicer output and a  neat summary how many tests passed/failed. OK to merge?

Run tests with tap-spec

---

test/test-find-sort-many.js

To demonstrate that sort does not work for more than 1000 results.
This test case demonstrates this issue: https://github.com/mafintosh/mongojs/issues/293
When fixed this could make sure we don't have this regression again.

Added (failing) test case find-sort-many

---

README.md

I needed to use connection options, but didn't see an example in the readme. I guessed that they'd be after the connection string, but that was incorrect. To save others the trouble, I added an example to the readme.

Updated readme with connection options example

---

index.js

This fix adds compatibility for node 6. Works with node 6 (uses `new Proxy`), node 5 (uses no Proxy), and node 5 with the `--harmony-proxies` flag (uses `Proxy.create`) and I didn't spot any obvious errors.

Fix for node 6

---

index.js

Hello there, I used the technique from [node-fetch](https://github.com/bitinn/node-fetch/blob/master/index.js#L23) to allow using `import mongojs from "mongojs"` with this library :1st_place_medal:

Adds support for ES6 default module import syntax

---

index.js
lib/database.js

When I am trying to migrate to higher version nodeJS, e.g. 6.9.1. I found below error coming from Proxy handler, which is caused by `Symbol` property. So I add another workaround to skip `Symbol` property during Proxy's get handler
```
TypeError: '[object Object]' returned for property 'Symbol(Symbol.toPrimitive)' of object '[object Object]' is not a function
at exports.format (util.js:108:18)
at Console.log (console.js:43:37)
at Database.<anonymous> (C:\git\test\app2.js:33:13)
at emitNone (events.js:86:13)
at Database.emit (events.js:185:7)
at C:\git\test\node_modules\mongojs\lib\database.js:35:14
at connectCallback (C:\git\test\node_modules\mongodb\lib\mongo_client.js:426:5)
at C:\git\test\node_modules\mongodb\lib\mongo_client.js:364:13
at _combinedTickCallback …
```

Work around for property 'Symbol(Symbol.toPrimitive)' in Proxy handler

---

lib/cursor.js

Using the new node core api for async tracing when available. Produces really good data in tracing tools :)

Add inital async_hooks support

---

lib/collection.js
lib/database.js
package.json
test/test-pass-mongodb.js
test/test-pass-mongojs.js

This updates the `mongodb` to version 3. All tests pass except the ones about receiving either mongodb or mongojs instances.
Is this a feature widely used? Or is it something we can do without, because it seems to bring some complexities. What do you guys think @mafintosh @saintedlama?

Upgrade mongodb to version ^3.

---

README.md

:memo: update var to const
